### ISSUE TITLE
Something might be wrong in "import_joy02.py"

### ISSUE THREAD

**Issue by qwe7989199** [marcan/blitzloop-tools#1]
First of all, thank you for your great job!
I am now writing some code which aims to convert JOY-02 format to ASS(Advanced SubStation) subtitle format.
When I tried to dump a song to the format defined in "**_import_joy02.py_**",
![image](https://user-images.githubusercontent.com/10990771/85193388-19f54680-b303-11ea-985a-22753f8258fd.png)
I found it's different with the result in JOYSOUND's Android App.
![problem](https://user-images.githubusercontent.com/10990771/85193238-95ee8f00-b301-11ea-9ec5-68336ed49e6e.png)

I think the right result should be like `\({μ'sic}(ミュージック)\)`for line 84.
I'm not very sure how to fix it, so I opened this issue.

I attached the JOY-02 file here.
[sample.txt](https://github.com/marcan/blitzloop-tools/files/4807413/sample.txt)

**Comment by marcan** [comment]
That looks buggy indeed. I'll take a look.

Keep in mind, though, that the furigana extractor is based on a heuristic. Joysound's format uses pixel positioning, so it is impossible to make it extract properly in every case, because you need a human to correctly interpret what text goes with the furigana. So although I can fix the weird duplication, I can't promise the result will be the same as what you expect the right output to be.

**Comment by qwe7989199** [comment]
> That looks buggy indeed. I'll take a look.
> 
> Keep in mind, though, that the furigana extractor is based on a heuristic. Joysound's format uses pixel positioning, so it is impossible to make it extract properly in every case, because you need a human to correctly interpret what text goes with the furigana. So although I can fix the weird duplication, I can't promise the result will be the same as what you expect the right output to be.

I noticed that even Furigana and Kanji characters in JOYSOUND's official app are not aligned. Anyway, thank you for your efforts.

**Comment by marcan** [comment]
Yeah, because they don't use quite the same font for authoring and for playback. Main lyrics are positioned character by character, but a string of furigana is positioned by its left edge, so if the font metrics for furigana aren't identical then it looks off-center.

Honestly, Joysound's entire authoring pipeline seems like a horrible legacy design, given little hints in their formats... I think they do almost everything manually.

**Comment by qwe7989199** [comment]
It's interesting that even though the Japanese invented karaoke first, they were limited by old technology.
I think it's the fact that these manufacturers have a lot of old machines running, and the cost of upgrading and migrating songs to a new format might be too high for them.
When I checked out DAM's home karaoke some days before, I noticed that they use hard-captioned video streaming, which means a lot of wasted on bandwidth and storage, since a lot of songs use the same video clip.

**Comment by marcan** [comment]
You can easily convert from a smarter format (like BlitzLoop's) to legacy formats though. I think it's just typical corporate inertia, which is even more common in Japan than in the west. Instead of revamping their authoring pipeline and keeping backwards compatibility with conversion, they keep using old designs because "that's the way it's always been done". Then they probably just have people toiling away doing manual layout for songs. Their format isn't even based on beat timing, it's based on scroll speeds in terms of pixels per second, which I'm convinced is the reason Joysound's timing is always quite mediocre and not well synchronized with the actual song.

And this is why Joysound still can't scroll more than one lyrics line at once (their format doesn't allow it), while BlitzLoop (and, incidentally, DAM) can, even on the newest Joysound machines with fancy HD and high res audio support.

I noticed that the Joysound switch audio files have background noise, which means they are playing back their MIDI sources through a hardware synth and recording it, instead of rendering them in software.

**Comment by qwe7989199** [comment]
Speaking of MIDI files, it occurs to me that the JSON data returned by the Joysound mobile client has an "example_data" in addition to the FME lyrics data, which you might be interested in.

After base64 decoding, it has a "THN" header, which should be the binary recorded note information, and used to score the singer(or 採点).

It doesn't look like a MIDI file we know.
This is the whole response
[response_body.txt](https://github.com/marcan/blitzloop-tools/files/4807486/response_body.txt)
